### ISSUE TITLE
I'm willing to add API specs for logged-in features, do we want that?

### ISSUE THREAD

**Issue by Riik** [Society-for-Internet-Blaseball-Research/blaseball-api-spec#23]
Many of the features of the website are only available when logged in. If found that getting active bets, buying snacks, etc. all also have their endpoints, for example under `/api/buySnack` or `/api/getActiveBets`. Those APIs are of course specific per user, so they do require a session id in the request header. 

Should we start documenting those too? I'd be happy to make a PR and add all the ones I can find!

**Comment by robbyblum** [comment]
You saw this there already, but for completeness' sake, I'll quote what ch00b said in discord about this: "We have a hard rule to not discuss or share code that involves auth tokens and/or POST requests." Therefore, no, we are not interested in documenting these APIs.

**Comment by Riik** [comment]
Yes, thanks for updating the issue!
